### ISSUE TITLE
aes_statsx_skill

### ISSUE THREAD

**Issue by patrig** [serfreeman1337/aes_statsx_cstrike#3]
Скиллов 13, а значений 12, правильно ли я понял, что чего то не хватает?

> new const g_skill_letters[][] = {
	"L-",
	"L",
	"L+",
	"M-",
	"M",
	"M+",
	"H-",
	"H",
	"H+",
	"P-",
	"P",
	"P+",
	"G"
}

> cvar[CVAR_SKILL] = register_cvar("aes_statsx_skill","60.0 75.0 85.0 100.0 115.0 130.0 140.0 150.0 165.0 180.0 195.0 210.0")

Добавлю: не работает История игр из меню ( /stats ) = вообще ничего не происходит.
Не правильно показывается текущую позицию в ТОПе ( /top ), /rank = одно место в ТОПе совсем другое.

**Comment by serfreeman1337** [comment]
Все верно. Все, что больше последнего значения (210) выводится считается как последний скилл (G).

> Добавлю: не работает История игр из меню ( /stats ) = вообще ничего не происходит.
А если через **/history** или **/sestats** ? Пробовал через меню открыть свою статистику?

> Не правильно показывается текущую позицию в ТОПе ( /top ), /rank = одно место в ТОПе совсем другое.

Я так понял это с [CSstatsxSQL](https://github.com/serfreeman1337/csstatsx-sql) ? Тогда это особенность моей реализации расчета ранга в SQL, о чем сказано в [README.me](https://github.com/serfreeman1337/csstatsx-sql/blob/master/README.md#%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8F).
